Symfony 3 related changes
paysera/lib-rest-bundle pull request #3
Opened 2017-05-22 12:07 UTC by asteisiunas

CERES-79

2017-05-22 13:23 UTC, sveliseicik commented on ApiManager.php
> +     * @param RecursiveValidator $validator
Symfony\Component\Validator\Validator\ValidatorIntefrace

2017-05-22 13:29 UTC, velser requested changes

2017-05-22 13:29 UTC, sveliseicik commented on ApiManager.php
> +     * @param RecursiveValidator $validator
We should use interfacese instead of concrete class

2017-05-24 06:20 UTC, asteisiunas commented
addRequestMapper doesn't work with DEFAULT_VALIDATION_GROUP.

2017-07-17 10:58 UTC, closed without merging